name: EfficientNet-B7 (HN)
backend: pytorch
loader: state_dict
arch: efficientnet_b7
weights_path: models/effb7_hn_best.pth
num_classes: 2
class_names: ["Good_Cut", "Bad_Cut"]
use_hypernetwork: true
metadata:
  custom_model_class: EffB7HyperNetWrapper
  schema:
    - key: patient_age
      type: float
      default: 55
    - key: tissue_type
      type: categorical
      choices: ["brain","colon","liver"]
      default: "brain"
preprocess:
  resize_shorter: 380
  center_crop: 380
  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]
